### ISSUE TITLE
TypeError: startswith first arg must be str or a tuple of str, not NoneType

### ISSUE THREAD

**Issue by zhanghonggeng** [tqchen/ffi-navigator#48]
TypeError: startswith first arg must be str or a tuple of str, not NoneType

**Comment by keosu** [comment]
> 

I tried, doesn't  work too

**Comment by Oreobird** [comment]
Got the same issue using vscode

**Comment by comaniac** [comment]
@tqchen better to release a new PYPI version based on the latest commit.

**Comment by tqchen** [comment]
PyPi updated
