### ISSUE TITLE
Any plan to make this package PyPi available?

### ISSUE THREAD

**Issue by comaniac** [tqchen/ffi-navigator#5]
I think it would be convenient because we can let vs code extension pip install this package when it is missing. Although we should be able to let vs code extension clone this package from Github and run setup.py, installing from pip is more reliable in my opinion.

**Comment by tqchen** [comment]
It is already on pypi, see latest readme

**Comment by comaniac** [comment]
Oh I just noticed that new section. Then we should be able to let vs code extension install the package when it is missing. I could investigate it a bit these days.
